<table class="table table-striped">
    <thead>
        <th>Id</th>
        <th>Número</th>
        <th>Rua</th>
        <th>Bairro</th>
        <th>Cidade</th>
    </thead>
    <tbody>
        <?php if (count($view_list) > 0) : ?>
            <?php foreach ($view_list as $li) : ?>
                <tr>
                    <td><?php echo $li->enderecoId; ?></td>
                    <td><?php echo $li->numero; ?></td>
                    <td><?php echo $li->rua; ?></td>
                    <td><?php echo $li->bairro; ?></td>
                    <td><?php echo $li->cidade; ?></td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
    </tbody>
</table>



<a href="admin/usuario/formCadastro" class="btn btn-sm btn-info">Novo Usuário</a>